# Generated by Django 3.1.1 on 2020-09-24 03:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0002_customermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('phoneno', models.CharField(max_length=15)),
                ('address', models.CharField(max_length=100)),
                ('ordereditems', models.CharField(max_length=30)),
            ],
        ),
    ]
