# Generated by Django 3.1.1 on 2020-09-25 02:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('deliveryapp', '0004_auto_20200924_0115'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='status',
            field=models.CharField(default='Delivered', max_length=15),
            preserve_default=False,
        ),
    ]
